-- Table for storing creative suggestions generated by IA
CREATE TABLE IF NOT EXISTS cliente_sugestoes_criativos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id UUID NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
  tipo VARCHAR NOT NULL CHECK (tipo IN ('post_instagram', 'copy_whatsapp', 'titulo_anuncio', 'angulo_venda', 'geral')),
  titulo VARCHAR,
  descricao TEXT,
  publico_alvo VARCHAR,
  formato VARCHAR,
  tom VARCHAR,
  prompt_usado TEXT,
  resposta_ia TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cliente_sugestoes_cliente ON cliente_sugestoes_criativos(cliente_id);
CREATE INDEX IF NOT EXISTS idx_cliente_sugestoes_tipo ON cliente_sugestoes_criativos(tipo);
CREATE INDEX IF NOT EXISTS idx_cliente_sugestoes_created ON cliente_sugestoes_criativos(created_at DESC);
